In [1]:
# 1. Import the required libraries and modules that you would need.
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings("ignore")

In [2]:
# 2. Read that data into Python and call the dataframe donors.
# 3. Check the datatypes of all the columns in the data.
# 4. Check for null values in the dataframe. Replace the null values using the methods learned in class.
# 5. Split the data into numerical and catagorical. Decide if any columns need their dtype changed.
# 6. Concatenate numerical and categorical back together again for your X dataframe. Designate the Target as y.
numerical = pd.read_csv('learningSet_numerical_clean.csv')
categorical = pd.read_csv('learningSet_categorical_clean.csv')
target = pd.read_csv('learningSet_Y.csv')

In [3]:
    # 6.1. Split the data into a training set and a test set.
    # 6.2. Split further into train_num and train_cat. Also test_num and test_cat.
    # 6.3. Scale the features either by using normalizer or a standard scaler. (train_num, test_num)Encode the categorical features using One-Hot Encoding or Ordinal Encoding. (train_cat, test_cat)
    # 6.4. Encode the categorical features using One-Hot Encoding or Ordinal Encoding. (train_cat, test_cat)
        # - fit only on train data transform both train and test
        # - again re-concatenate train_num and train_cat as X_train as well as test_num and test_cat as X_test

# Above order of works does not makes sense. Will split into train/test after scalling and OneHotEncoding

In [4]:
# Scalling
scaler = StandardScaler()
scaler.fit(numerical)
numerical_prep = pd.DataFrame(scaler.transform(numerical))
numerical_prep.columns = numerical.columns
numerical_prep

,ODATEDW,TCODE,DOB,AGE,INCOME,WEALTH1,HIT,MALEMILI,MALEVET,VIETVETS,...,MAXRDATE,LASTGIFT,LASTDATE,FISTDATE,TIMELAG,AVGGIFT,CONTROLN,HPHONE_D,RFA_2F,CLUSTER2
0,-0.699843,-0.056847,0.463551,-1.115292e-01,-1.312604,0.717411,-0.356881,-0.206977,0.745798,0.284659,...,-0.230581,-0.523992,-0.733220,-0.701177,-0.525458,-0.520509,-0.004760,-1.001238,1.948226,0.398135
1,0.755960,-0.055799,1.162350,-1.080356e+00,1.295872,0.717411,1.362283,-0.206977,-1.346527,1.675602,...,0.405737,0.550771,-0.733220,0.544171,1.275844,0.215310,0.954282,-1.001238,0.083847,-1.628365
2,-0.408683,-0.055799,-1.277349,-4.917093e-16,-0.008366,-2.239375,-0.141985,-0.206977,-0.910626,-0.046518,...,-1.358599,-0.882247,-0.733220,-0.420271,0.503857,-0.544692,-1.459730,0.998764,1.948226,1.518043
3,-1.282165,-0.056847,0.036299,5.804901e-01,-0.877858,-1.130581,-0.141985,-0.206977,-0.649086,-1.040049,...,-0.178519,-0.523992,-0.733220,-1.353502,0.117864,-0.606808,1.388782,0.998764,1.948226,0.504793
4,-1.573325,-0.056847,-0.338895,1.134106e+00,-0.008366,-1.869777,6.089983,-0.009563,-0.213185,-1.371225,...,0.920576,-0.165738,1.074423,-3.847319,0.761186,-0.601946,-1.603822,0.998764,0.083847,-0.295141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,1.338282,-0.055799,-1.277349,-4.917093e-16,-1.312604,0.717411,-0.356881,2.556819,0.484257,1.145719,...,0.926361,0.550771,1.094733,1.455554,-0.010800,1.081920,1.606058,-1.001238,-0.848342,-1.041747
95408,1.338282,-0.055799,1.068082,-9.419524e-01,1.730618,0.717411,-0.249433,-0.206977,0.048356,0.880777,...,0.932145,0.192517,1.115044,1.458675,-0.010800,0.617665,0.487079,0.998764,-0.848342,-1.575036
95409,1.047121,-0.055799,0.505291,-1.115292e-01,-1.312604,0.717411,-0.356881,-0.206977,-1.084987,1.079483,...,0.342105,-0.523992,1.257218,0.856289,-0.654122,-0.470019,1.697820,0.998764,1.016037,0.131490
95410,-1.573325,-0.056847,0.600966,-2.499331e-01,1.730618,0.717411,-0.356881,-0.206977,-0.213185,0.350894,...,0.961069,0.049215,3.105481,-1.634408,-0.525458,-0.111555,-1.647577,0.998764,1.948226,-1.095076
95411,-0.991004,-0.054750,-0.432694,1.272509e+00,0.861126,0.347813,-0.034538,-0.009563,0.222716,-0.510166,...,-0.751205,5.924590,1.297839,-1.038263,-0.268129,7.748147,1.615935,0.998764,-0.848342,-1.041747

In [5]:
# One Hot Encoding
categorical.nunique()

STATE          12
ZIP         19938
CLUSTER        53
HOMEOWNR        2
DATASRCE        4
RFA_2          14
RFA_2R          1
RFA_2A          4
GEOCODE2        5
DOMAIN_A        5
DOMAIN_B        4
dtype: int64

In [6]:
categorical = categorical.drop(columns='ZIP')

In [7]:
onehot_cols = []
for col in categorical.columns:
    col_uniques = sorted(categorical[col].astype(str).unique())
    for unique in col_uniques:
        onehot_cols.append(col+"_"+unique)

encoder = OneHotEncoder().fit(categorical)
encoded_categorical = pd.DataFrame(encoder.transform(categorical).toarray())
encoded_categorical.columns = onehot_cols
encoded_categorical

,STATE_CA,STATE_FL,STATE_GA,STATE_IL,STATE_IN,STATE_MI,STATE_MO,STATE_NC,STATE_OTHER,STATE_TX,...,GEOCODE2_U,DOMAIN_A_C,DOMAIN_A_R,DOMAIN_A_S,DOMAIN_A_T,DOMAIN_A_U,DOMAIN_B_1,DOMAIN_B_2,DOMAIN_B_3,DOMAIN_B_4
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
95408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
95409,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
95410,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
95411,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [8]:
# Concatenating and train-test split
X = pd.concat((numerical_prep,encoded_categorical),axis=1).reset_index(drop=True)
X

,ODATEDW,TCODE,DOB,AGE,INCOME,WEALTH1,HIT,MALEMILI,MALEVET,VIETVETS,...,GEOCODE2_U,DOMAIN_A_C,DOMAIN_A_R,DOMAIN_A_S,DOMAIN_A_T,DOMAIN_A_U,DOMAIN_B_1,DOMAIN_B_2,DOMAIN_B_3,DOMAIN_B_4
0,-0.699843,-0.056847,0.463551,-1.115292e-01,-1.312604,0.717411,-0.356881,-0.206977,0.745798,0.284659,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.755960,-0.055799,1.162350,-1.080356e+00,1.295872,0.717411,1.362283,-0.206977,-1.346527,1.675602,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,-0.408683,-0.055799,-1.277349,-4.917093e-16,-0.008366,-2.239375,-0.141985,-0.206977,-0.910626,-0.046518,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,-1.282165,-0.056847,0.036299,5.804901e-01,-0.877858,-1.130581,-0.141985,-0.206977,-0.649086,-1.040049,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-1.573325,-0.056847,-0.338895,1.134106e+00,-0.008366,-1.869777,6.089983,-0.009563,-0.213185,-1.371225,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,1.338282,-0.055799,-1.277349,-4.917093e-16,-1.312604,0.717411,-0.356881,2.556819,0.484257,1.145719,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
95408,1.338282,-0.055799,1.068082,-9.419524e-01,1.730618,0.717411,-0.249433,-0.206977,0.048356,0.880777,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
95409,1.047121,-0.055799,0.505291,-1.115292e-01,-1.312604,0.717411,-0.356881,-0.206977,-1.084987,1.079483,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
95410,-1.573325,-0.056847,0.600966,-2.499331e-01,1.730618,0.717411,-0.356881,-0.206977,-0.213185,0.350894,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
95411,-0.991004,-0.054750,-0.432694,1.272509e+00,0.861126,0.347813,-0.034538,-0.009563,0.222716,-0.510166,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [9]:
target=target.drop(columns="TARGET_D")
X_train, X_test, y_train, y_test = train_test_split(X,target, test_size=0.2, random_state=100)

In [10]:
    # 6.5. Fit a logistic regression model on the training data.
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [11]:
    # 6.6. Check the accuracy on the test data.
model.score(X_test, y_test)

0.9496410417649217

### Managing imbalance in the dataset

In [12]:
# Check for the imbalance.
target.value_counts()

TARGET_B
0           90569
1            4843
dtype: int64

In [13]:
# Use the resampling strategies used in class for upsampling and downsampling to create a balance between the two classes.

In [14]:
# Each time fit the model and see how the accuracy of the model has changed.

### Upsampling

In [15]:
data = pd.concat((target,X),axis=1).reset_index(drop=True)
data

,TARGET_B,ODATEDW,TCODE,DOB,AGE,INCOME,WEALTH1,HIT,MALEMILI,MALEVET,...,GEOCODE2_U,DOMAIN_A_C,DOMAIN_A_R,DOMAIN_A_S,DOMAIN_A_T,DOMAIN_A_U,DOMAIN_B_1,DOMAIN_B_2,DOMAIN_B_3,DOMAIN_B_4
0,0,-0.699843,-0.056847,0.463551,-1.115292e-01,-1.312604,0.717411,-0.356881,-0.206977,0.745798,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0,0.755960,-0.055799,1.162350,-1.080356e+00,1.295872,0.717411,1.362283,-0.206977,-1.346527,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0,-0.408683,-0.055799,-1.277349,-4.917093e-16,-0.008366,-2.239375,-0.141985,-0.206977,-0.910626,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0,-1.282165,-0.056847,0.036299,5.804901e-01,-0.877858,-1.130581,-0.141985,-0.206977,-0.649086,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0,-1.573325,-0.056847,-0.338895,1.134106e+00,-0.008366,-1.869777,6.089983,-0.009563,-0.213185,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,0,1.338282,-0.055799,-1.277349,-4.917093e-16,-1.312604,0.717411,-0.356881,2.556819,0.484257,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
95408,0,1.338282,-0.055799,1.068082,-9.419524e-01,1.730618,0.717411,-0.249433,-0.206977,0.048356,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
95409,0,1.047121,-0.055799,0.505291,-1.115292e-01,-1.312604,0.717411,-0.356881,-0.206977,-1.084987,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
95410,1,-1.573325,-0.056847,0.600966,-2.499331e-01,1.730618,0.717411,-0.356881,-0.206977,-0.213185,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
95411,0,-0.991004,-0.054750,-0.432694,1.272509e+00,0.861126,0.347813,-0.034538,-0.009563,0.222716,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [16]:
category_0 = data[data['TARGET_B']==0]
category_1 = data[data['TARGET_B']==1]

category_1_new = category_1.sample(round(len(category_0)*0.8),replace=True)
data2 = pd.concat([category_0,category_1_new],axis=0)
data2['TARGET_B'].value_counts()

0    90569
1    72455
Name: TARGET_B, dtype: int64

In [17]:
X = data2.drop(columns='TARGET_B')
y = data2['TARGET_B']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=100)
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.6129121300414047

### Downsampling

In [18]:
category_0 = data[data['TARGET_B']==0]
category_1 = data[data['TARGET_B']==1]

category_0_new = category_0.sample(len(category_1)*2)

data2 = pd.concat([category_0_new,category_1],axis=0)
data2['TARGET_B'].value_counts()

0    9686
1    4843
Name: TARGET_B, dtype: int64

In [19]:
X = data2.drop(columns='TARGET_B')
y = data2['TARGET_B']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=100)
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.6545079146593256

In [21]:
# Downsampling at len(a) = len(2b) yields a slightly better score than upsampling at len(b) = len(a*0.8)